### ISSUE TITLE
In 4.6, new styles make for interesting update pages

### ISSUE THREAD

**Issue by benlk** [INN/link-roundups#122]
<img width="827" alt="screen shot 2016-08-22 at 2 26 28 am" src="https://cloud.githubusercontent.com/assets/1754187/17845457/efc85d80-680f-11e6-9087-1ab64851b151.png">

```css
# http://vagrant.dev/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,widgets,site-icon,&load%5B%5D=l10n,buttons,wp-auth-check,wp-color-picker&ver=4.6
.button.installing:before, .button.updating-message:before, .import-php .updating-message:before, .update-message p:before, .updating-message p:before {
    color: #f56e28;
    content: "\f463";
}
# http://vagrant.dev/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,widgets,site-icon,&load%5B%5D=l10n,buttons,wp-auth-check,wp-color-picker&ver=4.6
.button.installed:before, .button.installing:before, .button.updated-message:before, .button.updating-message:before, .import-php .updating-message:before, .update-message p:before, .updated-message p:before, .updating-message p:before {
    display: inline-block;
    font: 400 20px/1 dashicons;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    vertical-align: top;
}
```

It's just a class conflict; we can change the markup in the plugin from `.update-message` to something else.

Cosmetic issue, but should this be taken care of before we mark it ready for WordPress 4.6?
